name: Deploy to cloud GPU instance
on:
  workflow_dispatch:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@v3
      - name: rsync deployment
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr
          path: "."
          remote_path: ${{ vars.DEPLOY_HOST_PATH }}
          remote_host: ${{ vars.DEPLOY_HOST_IP }}
          remote_user: ${{ secrets.DEPLOY_HOST_USER }}
          remote_key: ${{ secrets.DEPLOY_HOST_KEY }}
